### ISSUE TITLE
npm version is WAY out of date

### ISSUE THREAD

**Issue by fresheneesz** [asyncly/EventEmitter2#185]
Update the npm package already! The latest version on there is 0.4.14 and the current version here is 2.1.0

**Comment by RangerMauve** [comment]
I'm not sure where you're seeing this, but I released 2.1.0 to NPM a few days ago. https://www.npmjs.com/package/eventemitter2

**Comment by fresheneesz** [comment]
@RangerMauve Ahh i see what happened. I added "eventemitter2":"*" into my package.json, but I didn't realize I already had an old version downloaded in my node_modules. That's why i ended up still having an old version.

**Comment by RangerMauve** [comment]
Makes sense. :P
